name: Build and Test

on:
  pull_request:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: maven

      - name: Run the Maven install phase
        run: mvn --batch-mode --update-snapshots install

      - name: Start Docker containers
        run: |
          docker compose --file ./docker/docker-compose.yml up -d

      - name: Sleep for 5 seconds
        run: sleep 5

      - name: Run Postman collection
        uses: matt-ball/newman-action@master
        with:
          collection: ./postman/ewm.postman_collection.json

      - name: Stop Docker containers
        if: always()
        run: |
          docker compose --file ./docker/docker-compose.yml down
